version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_DB: analytics
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: ""
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - ./scripts:/docker-entrypoint-initdb.d
      - ./app:/app
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - clickhouse-network

  tabix:
    image: spoonest/clickhouse-tabix-web-client:latest
    container_name: clickhouse-tabix
    ports:
      - "8080:80"
    depends_on:
      - clickhouse
    environment:
      CH_NAME: clickhouse
      CH_HOST: clickhouse
      CH_PORT: 8123
    networks:
      - clickhouse-network

  data-generator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clickhouse-data-generator
    depends_on:
      - clickhouse
    volumes:
      - ./app:/app
    environment:
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_PORT: 8123
    command: python /app/data_generator.py
    networks:
      - clickhouse-network

volumes:
  clickhouse-data:

networks:
  clickhouse-network:
    driver: bridge