version: '3.8'

services:
  # Apache Spark Cluster
  spark-master:
    image: bitnami/spark:3.4
    container_name: spark-master
    env_file:
      - .env
    environment:
      - SPARK_MODE=${SPARK_MODE_MASTER}
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./spark/app:/app
      - ./spark/data:/data
      - ./shared-data:/shared-data
    networks:
      - big-data-network

  spark-worker:
    image: bitnami/spark:3.4
    container_name: spark-worker
    env_file:
      - .env
    environment:
      - SPARK_MODE=${SPARK_MODE_WORKER}
    ports:
      - "8081:8081"
    volumes:
      - ./spark/app:/app
      - ./spark/data:/data
      - ./shared-data:/shared-data
    depends_on:
      - spark-master
    networks:
      - big-data-network

  # Apache Kafka Cluster
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    env_file:
      - .env
    ports:
      - "2181:2181"
    networks:
      - big-data-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    env_file:
      - .env
    volumes:
      - ./kafka/app:/app
      - ./shared-data:/shared-data
    networks:
      - big-data-network

  # Apache Airflow
  airflow-postgres:
    image: postgres:13
    container_name: airflow-postgres
    env_file:
      - .env
    volumes:
      - airflow-postgres-data:/var/lib/postgresql/data
    networks:
      - big-data-network

  airflow-redis:
    image: redis:latest
    container_name: airflow-redis
    networks:
      - big-data-network

  airflow-webserver:
    image: apache/airflow:2.7.0-python3.9
    container_name: airflow-webserver
    depends_on:
      - airflow-postgres
      - airflow-redis
    env_file:
      - .env
    ports:
      - "8082:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./shared-data:/shared-data
    command: webserver
    networks:
      - big-data-network

  airflow-scheduler:
    image: apache/airflow:2.7.0-python3.9
    container_name: airflow-scheduler
    depends_on:
      - airflow-postgres
      - airflow-redis
    env_file:
      - .env
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./shared-data:/shared-data
    command: scheduler
    networks:
      - big-data-network

  # ClickHouse
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    env_file:
      - .env
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - ./clickhouse/scripts:/docker-entrypoint-initdb.d
      - ./clickhouse/app:/app
      - ./shared-data:/shared-data
    networks:
      - big-data-network

  # Kafka UI
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8090:8080"
    env_file:
      - .env
    networks:
      - big-data-network

  # Tabix (ClickHouse UI)
  tabix:
    image: spoonest/clickhouse-tabix-web-client:latest
    container_name: tabix
    ports:
      - "8091:80"
    depends_on:
      - clickhouse
    env_file:
      - .env
    networks:
      - big-data-network

  # Jupyter Notebook for Spark
  jupyter:
    image: jupyter/pyspark-notebook:latest
    container_name: jupyter
    ports:
      - "8888:8888"
    env_file:
      - .env
    volumes:
      - ./spark/notebooks:/home/jovyan/work
      - ./shared-data:/home/jovyan/shared-data
    depends_on:
      - spark-master
    networks:
      - big-data-network

  # Data Generator (unified)
  data-generator:
    build: 
      context: ./data-generator
      dockerfile: Dockerfile
    container_name: data-generator
    depends_on:
      - kafka
      - clickhouse
    volumes:
      - ./shared-data:/shared-data
    env_file:
      - .env
    networks:
      - big-data-network

volumes:
  airflow-postgres-data:
  clickhouse-data:

networks:
  big-data-network:
    driver: bridge