version: '3.8'

services:
  spark-master:
    image: bitnami/spark:3.4
    container_name: spark-master
    env_file:
      - .env
    environment:
      - SPARK_MODE=${SPARK_MODE_MASTER}
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./app:/app
      - ./data:/data
    networks:
      - spark-network

  spark-worker:
    image: bitnami/spark:3.4
    container_name: spark-worker
    env_file:
      - .env
    environment:
      - SPARK_MODE=${SPARK_MODE_WORKER}
    ports:
      - "8081:8081"
    volumes:
      - ./app:/app
      - ./data:/data
    depends_on:
      - spark-master
    networks:
      - spark-network

  jupyter:
    image: jupyter/pyspark-notebook:latest
    container_name: spark-jupyter
    ports:
      - "8888:8888"
    env_file:
      - .env
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./data:/home/jovyan/data
    depends_on:
      - spark-master
    networks:
      - spark-network

  data-generator:
    build: 
      context: .
      dockerfile: Dockerfile.generator
    container_name: spark-data-generator
    volumes:
      - ./data:/data
    depends_on:
      - spark-master
    networks:
      - spark-network

networks:
  spark-network:
    driver: bridge