version: '3.8'

services:
  storm-nimbus:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: storm-nimbus
    ports:
      - "8086:8080"
      - "6627:6627"
    env_file:
      - .env
    environment:
      - STORM_MODE=nimbus
    volumes:
      - ./data:/opt/storm/data
      - ./logs:/opt/storm/logs
      - ../shared-data:/shared-data
    command: storm nimbus
    depends_on:
      - zookeeper
    networks:
      - storm-network

  storm-supervisor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: storm-supervisor
    ports:
      - "6700-6703:6700-6703"
    env_file:
      - .env
    environment:
      - STORM_MODE=supervisor
    volumes:
      - ./data:/opt/storm/data
      - ./logs:/opt/storm/logs
      - ../shared-data:/shared-data
    command: storm supervisor
    depends_on:
      - storm-nimbus
    networks:
      - storm-network

  storm-ui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: storm-ui
    ports:
      - "8087:8080"
    env_file:
      - .env
    environment:
      - STORM_MODE=ui
    volumes:
      - ./data:/opt/storm/data
      - ./logs:/opt/storm/logs
    command: storm ui
    depends_on:
      - storm-nimbus
    networks:
      - storm-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: storm-zookeeper
    ports:
      - "2184:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - storm-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: storm-kafka
    depends_on:
      - zookeeper
    ports:
      - "9095:9092"
    environment:
      KAFKA_BROKER_ID: 4
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9095
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    networks:
      - storm-network

networks:
  storm-network:
    driver: bridge